#https://docs.gitlab.cn/jh/ci/variables/predefined_variables.html 可调用的变量
#gomac.exe --name=build/send --path=gobuild/main.go

stages:
  - build

job_build:
  stage: build
  only:
    - tags
    - /^release-ios.*$/
  tags:
    - QxPacker
  script:
    - echo "Building IOS APP"
    - pwd
    - cd SGProject/Script
    - chmod +x Build_Package_Development_IOS.sh && ./Build_Package_Development_IOS.sh
    - echo "Param：$CI_COMMIT_AUTHOR $CI_COMMIT_TAG"
    - chmod +x send && ./send $CI_COMMIT_TAG
    
#job_test1:
#  stage: test
#  rules:
#    - if: $CI_COMMIT_TAG =~ /^release.*$/
#      when: always
#  tags:
#    - QxPacker
#  script:
#    - echo "Running Rules"